name: 'Branch PR comment'
description: 'Send comment to PR associated with branch'
author: 'Janealter'
branding:
  icon: 'message-circle'
  color: 'purple'
inputs:
  message:
    description: 'Comment message text'
    required: true
  branch:
    description: 'Branch associated with PR'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
